[package]
name = "rel"
version = "0.2.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Relations"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rel/"
repository = "https://github.com/strake/rel.rs"
